### ISSUE TITLE
demo_appで使用しているPhoenixのバージョンが異なる

### ISSUE THREAD

**Issue by harapeko** [darui00kara/phoenix_tutorial#2]
https://github.com/darui00kara/phoenix_tutorial/blob/master/tutorial/README.md#dev-environment
>Phoenix Framework: v1.0.3

demo_appのmix.exsを見ると `~> 0.13.1` となっています
https://github.com/darui00kara/phoenix_tutorial/blob/master/demo_app/mix.exs#L32

内容的には進める上でそれほど問題ないとは思いますが
明記している事と異なるのが気になりました。

**Comment by darui00kara** [comment]
返信遅くなってしまい申し訳ないです。
ご指摘ありがとうございます。

v1.0にアップグレードする際、更新が漏れていたようです。修正しておきます。

また何かお気づきの点があれば、遠慮なくお願いいたします。

**Comment by harapeko** [comment]
ご連絡ありがとうございました！

**Comment by darui00kara** [comment]
一点だけお知らせさせていただきたいことがあります。このリポジトリのソースは既に古いので最新版だと動かないです。

文章がなく申し訳ないのですが、Phoenixのv1.2に対応しているリポジトリもありますので、今後はこちらを見ていただけますと幸いです。

https://github.com/darui00kara/phoenix_tutorial_v1_2

**Comment by harapeko** [comment]
@darui00kara ご丁寧にありがとうございます┏(<：)ﾍﾟｺﾁｮﾝ

参考にさせていただきます！
